# Generated by Django 3.2.7 on 2021-09-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('fullname', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=5)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
