# Generated by Django 3.2.7 on 2021-09-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_books_image'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='fullname',
            field=models.CharField(db_column='full name', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=10),
        ),
        migrations.CreateModel(
            name='borrowred_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_borrowe', models.DateTimeField(auto_now_add=True, db_column='the time of borrowe')),
                ('data_return', models.DateField(db_column='return data')),
                ('book_title', models.ForeignKey(db_column='book title', on_delete=django.db.models.deletion.CASCADE, to='books.books')),
                ('user_id', models.ForeignKey(db_column='user id', on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
