# Generated by Django 3.2.7 on 2021-09-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('price', models.FloatField()),
                ('types', models.CharField(choices=[('math', 'math'), ('hiostry', 'hiostry'), ('novel', 'novel'), ('science', 'science')], max_length=10)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
