# Generated by Django 3.2.7 on 2021-09-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('types', models.CharField(choices=[('math', 'math'), ('hiostry', 'hiostry'), ('novel', 'novel'), ('science', 'science')], max_length=10)),
                ('available', models.BooleanField()),
                ('num_copy', models.IntegerField()),
            ],
        ),
    ]
