# Generated by Django 3.2.7 on 2021-09-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_books_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='num_copy',
        ),
    ]
